PREOPS-3388: Write a technote describing gateway for releasing first alerts to brokers
lsst/rtn-061 pull request #2
Opened 2023-11-17 21:14 UTC by ebellm

2023-12-10 16:21 UTC, leannep requested changes
Looks good - thank you for this technote

2023-12-10 16:21 UTC, leannep commented on RTN-061.tex
> +Its goal to to aid Project planning and decisionmaking while clarifying expectations for community scientists and our alert broker partners.
```suggestion
Its goal is to aid Project planning and decision making while clarifying expectations for community scientists and our alert broker partners.
```

2023-12-10 16:21 UTC, leannep commented on RTN-061.tex
> +As this is likely to occur during the fluid period of commissioning but begins a long-term operational campaign, this document aims to specify gateway criteria for beginning Alert Production.
```suggestion
As this is likely to occur during the fluid period of commissioning and begins a long-term operational campaign, this document aims to specify gateway criteria for beginning Alert Production.
```

2023-12-10 16:21 UTC, leannep commented on RTN-061.tex
> +For operational efficiency, we do not intend to release significant amounts of ``alert'' data outside of the normal Alert Production process.
Do you mean "release significant numbers of alerts" or "release significant amounts of alert-related" data. I worry about setting any expectation of alert packets being released outside of normal AP  processes.  Suggest removing this. If we end up doing it, it will be a bonus.

2023-12-10 16:21 UTC, leannep commented on RTN-061.tex
> +The Science Pipelines payloads should be executed by the automated real-time Prompt Processing framework at the USDF.
```suggestion
The Science Pipelines payloads will be executed by the automated real-time Prompt Processing framework at the USDF.
```

2023-12-10 16:21 UTC, leannep commented on RTN-061.tex
> +The Science Pipelines payloads should be executed by the automated real-time Prompt Processing framework at the USDF.
Is there any reason we think they might not be executed by the automated real-time Prompt Processing framework at the USDF?

2023-12-10 16:21 UTC, leannep commented on RTN-061.tex
> +All transmitted alerts should be archived at the USDF \citedsp{DMTN-183}.
should or will?

2023-12-11 17:55 UTC, ebellm commented on RTN-061.tex
> +The Science Pipelines payloads should be executed by the automated real-time Prompt Processing framework at the USDF.
I'm using "should" here in the sense that it is a prerequisite for starting routine AP--the statement is intended to be prescriptive.  Indeed, we're not planning to run AP outside of PP (aside potentially from rare catch-up or replacement processing).

2023-12-11 17:56 UTC, ebellm commented on RTN-061.tex
> +All transmitted alerts should be archived at the USDF \citedsp{DMTN-183}.
As above, I think "should."

2023-12-11 19:28 UTC, leannep approved these changes

2023-12-11 19:28 UTC, leannep commented on RTN-061.tex
> +The Science Pipelines payloads should be executed by the automated real-time Prompt Processing framework at the USDF.
OK, that makes sense

2023-12-11 19:42 UTC, merged